In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df=pd.read_csv("./DataSets/census_data.csv")
df.head()

age          workclass   education  education_num       marital_status  \
0   39          State-gov   Bachelors             13        Never-married   
1   50   Self-emp-not-inc   Bachelors             13   Married-civ-spouse   
2   38            Private     HS-grad              9             Divorced   
3   53            Private        11th              7   Married-civ-spouse   
4   28            Private   Bachelors             13   Married-civ-spouse   

           occupation    relationship    race   gender  capital_gain  \
0        Adm-clerical   Not-in-family   White     Male          2174   
1     Exec-managerial         Husband   White     Male             0   
2   Handlers-cleaners   Not-in-family   White     Male             0   
3   Handlers-cleaners         Husband   Black     Male             0   
4      Prof-specialty            Wife   Black   Female             0   

   capital_loss  hours_per_week  native_country income_bracket  
0             0              40   United-States          <=50K  
1             0              13   United-States          <=50K  
2             0              40   United-States          <=50K  
3             0              40   United-States          <=50K  
4             0              40            Cuba          <=50K

In [3]:
df.income_bracket.unique()

array([' <=50K', ' >50K'], dtype=object)

In [4]:
df.education.unique()

array([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',
       ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th',
       ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th',
       ' Preschool', ' 12th'], dtype=object)

In [5]:
df.occupation.unique()

array([' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners',
       ' Prof-specialty', ' Other-service', ' Sales', ' Craft-repair',
       ' Transport-moving', ' Farming-fishing', ' Machine-op-inspct',
       ' Tech-support', ' ?', ' Protective-serv', ' Armed-Forces',
       ' Priv-house-serv'], dtype=object)

In [6]:
df.occupation = df.occupation.str.replace("?", "nan")
df.workclass = df.workclass.str.replace("?", "na")
df.income_bracket = df.income_bracket.str.replace("<=50K", "underfifty")
df.income_bracket = df.income_bracket.str.replace(">50K", "overfifty")

In [7]:
df.isnull().sum()

age               0
workclass         0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
gender            0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income_bracket    0
dtype: int64

In [8]:
df.occupation.value_counts()

 Prof-specialty       4140
 Craft-repair         4099
 Exec-managerial      4066
 Adm-clerical         3770
 Sales                3650
 Other-service        3295
 Machine-op-inspct    2002
 nan                  1843
 Transport-moving     1597
 Handlers-cleaners    1370
 Farming-fishing       994
 Tech-support          928
 Protective-serv       649
 Priv-house-serv       149
 Armed-Forces            9
Name: occupation, dtype: int64

In [9]:
df.columns.to_list()

['age',
 'workclass',
 'education',
 'education_num',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'capital_gain',
 'capital_loss',
 'hours_per_week',
 'native_country',
 'income_bracket']

In [10]:
df.groupby(['education','workclass','occupation','gender'])['income_bracket'].value_counts()

education      workclass     occupation        gender   income_bracket
 10th           Federal-gov   Craft-repair      Male     underfifty         4
                              Other-service     Female   underfifty         2
                Local-gov     Adm-clerical      Male     underfifty         2
                              Craft-repair      Male     underfifty         6
                              Exec-managerial   Male     underfifty         1
                                                                         ... 
 Some-college   Without-pay   Farming-fishing   Male     underfifty         1
                na            nan               Female   underfifty       257
                                                         overfifty         10
                                                Male     underfifty       222
                                                         overfifty         25
Name: income_bracket, Length: 1728, dtype: int64

In [11]:
df.corr()

age  education_num  capital_gain  capital_loss  \
age             1.000000       0.036527      0.077674      0.057775   
education_num   0.036527       1.000000      0.122630      0.079923   
capital_gain    0.077674       0.122630      1.000000     -0.031615   
capital_loss    0.057775       0.079923     -0.031615      1.000000   
hours_per_week  0.068756       0.148123      0.078409      0.054256   

                hours_per_week  
age                   0.068756  
education_num         0.148123  
capital_gain          0.078409  
capital_loss          0.054256  
hours_per_week        1.000000

In [12]:
df=df.drop(['education_num','race','native_country'],axis=1)
df.head()

age          workclass   education       marital_status  \
0   39          State-gov   Bachelors        Never-married   
1   50   Self-emp-not-inc   Bachelors   Married-civ-spouse   
2   38            Private     HS-grad             Divorced   
3   53            Private        11th   Married-civ-spouse   
4   28            Private   Bachelors   Married-civ-spouse   

           occupation    relationship   gender  capital_gain  capital_loss  \
0        Adm-clerical   Not-in-family     Male          2174             0   
1     Exec-managerial         Husband     Male             0             0   
2   Handlers-cleaners   Not-in-family     Male             0             0   
3   Handlers-cleaners         Husband     Male             0             0   
4      Prof-specialty            Wife   Female             0             0   

   hours_per_week income_bracket  
0              40     underfifty  
1              13     underfifty  
2              40     underfifty  
3              40     underfifty  
4              40     underfifty

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
label=LabelEncoder()

In [15]:
df_new = df.copy()
df_new['workclass'] = label.fit_transform(df_new['workclass'])
df_new['education'] = label.fit_transform(df_new['education'])
df_new['marital_status'] = label.fit_transform(df_new['marital_status'])
df_new['occupation'] = label.fit_transform(df_new['occupation'])
df_new['relationship'] = label.fit_transform(df_new['relationship'])
df_new['gender'] = label.fit_transform(df_new['gender'])
df_new['income_bracket'] = label.fit_transform(df_new['income_bracket'])

In [16]:
df.dtypes

age                int64
workclass         object
education         object
marital_status    object
occupation        object
relationship      object
gender            object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
income_bracket    object
dtype: object

In [17]:
x = df_new.iloc[:, :10].values
y = df_new.iloc[:, 10:].values


In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
model=DecisionTreeClassifier()

In [21]:
model.fit(x_train , y_train)

DecisionTreeClassifier()

In [22]:
y_predict = model.predict(x_test)

In [23]:
from sklearn.metrics import accuracy_score
print("Accuracy Score:", accuracy_score(y_test, y_predict))

Accuracy Score: 0.8114540150468295


In [24]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[1026  556]
 [ 672 4259]]


# cross validation scores

In [25]:
from sklearn.model_selection import cross_val_score
model_cv = DecisionTreeClassifier()
scores = cross_val_score(model_cv, x, y, cv=10, scoring='accuracy')
print(scores)

[0.81209702 0.81418919 0.81848894 0.80651106 0.81449631 0.81326781
 0.8203317  0.8203317  0.82678133 0.8227887 ]


# finding suitable features for model

In [26]:
from sklearn.model_selection import GridSearchCV

In [27]:
tuned_parameters = { 'criterion': ['gini', 'entropy'], 
                    'max_depth': [8,9,10,11,12,13,14,15,16,17,18,19,20], 
                    'max_features': [1,2,3,4,5,6,7,8,9,10]
                   }

In [28]:
model_gscv = DecisionTreeClassifier()

In [29]:
model_dt = GridSearchCV(estimator=model_gscv, param_grid=tuned_parameters, cv=50, scoring='accuracy')

In [30]:
model_dt.fit(x, y)

GridSearchCV(cv=50, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
                                       19, 20],
                         'max_features': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
             scoring='accuracy')

In [31]:
print("Best Score:", model_dt.best_params_)

Best Score: {'criterion': 'gini', 'max_depth': 12, 'max_features': 10}


In [41]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)
fmodel=DecisionTreeClassifier(criterion= 'gini', max_depth= 12, max_features= 10)

In [42]:
fmodel.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=12, max_features=10)

# final model

In [43]:
y_predict = fmodel.predict(x_test)

In [44]:
print('accuracy', accuracy_score(y_test, y_predict))

accuracy 0.8506064793489944


In [45]:
print("Confusion Matrix")
cm = confusion_matrix(y_test, y_predict)
print(cm)

Confusion Matrix
[[ 900  647]
 [ 326 4640]]


# important features

In [46]:
features=df_new.drop('income_bracket',axis=1).columns.tolist()

In [47]:
impfeatures=fmodel.feature_importances_
impfeatures

array([0.06695296, 0.02081579, 0.1393183 , 0.00538441, 0.02471939,
       0.35986619, 0.00302634, 0.22941853, 0.09034061, 0.06015749])

In [48]:
result = pd.DataFrame({'Features':features, 'Importance':impfeatures})
result

Features  Importance
0             age    0.066953
1       workclass    0.020816
2       education    0.139318
3  marital_status    0.005384
4      occupation    0.024719
5    relationship    0.359866
6          gender    0.003026
7    capital_gain    0.229419
8    capital_loss    0.090341
9  hours_per_week    0.060157

# predicted outcomes for test class

In [49]:
y_predict

array([1, 0, 0, ..., 1, 0, 1])